/**
 * The single source of truth for every component. The docs sidebar, the
 * components index, the CLI registry and the tests all read from this list,
 * and `demos.ts` is type-checked against it.
 */
export const CATEGORIES = [
  "Navigation",
  "Actions",
  "Data Display",
  "Backgrounds",
  "Typography",
  "Components",
] as const;

export type Category = (typeof CATEGORIES)[number];

export interface RegistryItem {
  /** Slug used in URLs, file names and `npx modus-ui add <name>`. */
  name: string;
  title: string;
  category: Category;
  type: "components:ui";
  dependencies: readonly string[];
  files: readonly string[];
}

export const registry = [
  {
    name: "liquid-tabs",
    title: "Liquid Tabs",
    category: "Navigation",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/liquid-tabs.tsx"],
  },
  {
    name: "flowing-menu",
    title: "Flowing Menu",
    category: "Navigation",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/flowing-menu.tsx"],
  },
  {
    name: "morphing-navbar",
    title: "Morphing Navbar",
    category: "Navigation",
    type: "components:ui",
    dependencies: ["framer-motion", "lucide-react", "clsx", "tailwind-merge"],
    files: ["registry/morphing-navbar.tsx"],
  },
  {
    name: "floating-dock",
    title: "Floating Dock",
    category: "Navigation",
    type: "components:ui",
    dependencies: ["framer-motion", "lucide-react"],
    files: ["registry/floating-dock.tsx"],
  },
  {
    name: "notch-footer",
    title: "Notch Footer",
    category: "Navigation",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/notch-footer.tsx"],
  },
  {
    name: "process-stepper",
    title: "Process Stepper",
    category: "Navigation",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/process-stepper.tsx"],
  },
  {
    name: "magnet",
    title: "Magnet",
    category: "Actions",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/magnet.tsx"],
  },
  {
    name: "magic-button",
    title: "Magic Button",
    category: "Actions",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/magic-button.tsx"],
  },
  {
    name: "animated-button",
    title: "Animated Button",
    category: "Actions",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/animated-button.tsx"],
  },
  {
    name: "pulse-button",
    title: "Pulse Button",
    category: "Actions",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/pulse-button.tsx"],
  },
  {
    name: "bounce-cards",
    title: "Bounce Cards",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/bounce-cards.tsx"],
  },
  {
    name: "masonry-grid",
    title: "Masonry Grid",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/masonry-grid.tsx"],
  },
  {
    name: "animated-list",
    title: "Animated List",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/animated-list.tsx"],
  },
  {
    name: "kinetic-carousel",
    title: "Kinetic Carousel",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/kinetic-carousel.tsx"],
  },
  {
    name: "expandable-showcase",
    title: "Expandable Showcase",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/expandable-showcase.tsx"],
  },
  {
    name: "focus-card",
    title: "Focus Card",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/focus-card.tsx"],
  },
  {
    name: "rotating-card",
    title: "Rotating Card",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/rotating-card.tsx"],
  },
  {
    name: "tilt-card",
    title: "Tilt Card",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/tilt-card.tsx"],
  },
  {
    name: "cursor-grid",
    title: "Cursor Grid",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/cursor-grid.tsx"],
  },
  {
    name: "waves",
    title: "Waves",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/waves.tsx"],
  },
  {
    name: "letter-glitch",
    title: "Letter Glitch",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/letter-glitch.tsx"],
  },
  {
    name: "aurora-background",
    title: "Aurora Background",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/aurora-background.tsx"],
  },
  {
    name: "circuit-background",
    title: "Circuit Background",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/circuit-background.tsx"],
  },
  {
    name: "orbiting-elements",
    title: "Orbiting Elements",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/orbiting-elements.tsx"],
  },
  {
    name: "blob-cursor",
    title: "Blob Cursor",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/blob-cursor.tsx"],
  },
  {
    name: "magnet-lines",
    title: "Magnet Lines",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/magnet-lines.tsx"],
  },
  {
    name: "grid-motion",
    title: "Grid Motion",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/grid-motion.tsx"],
  },
  {
    name: "gravity-text-swap",
    title: "Gravity Text Swap",
    category: "Typography",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/gravity-text-swap.tsx"],
  },
  {
    name: "flip-words",
    title: "Flip Words",
    category: "Typography",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/flip-words.tsx"],
  },
  {
    name: "fuzzy-text",
    title: "Fuzzy Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/fuzzy-text.tsx"],
  },
  {
    name: "scroll-velocity",
    title: "Scroll Velocity",
    category: "Typography",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/scroll-velocity.tsx"],
  },
  {
    name: "text-pressure",
    title: "Text Pressure",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/text-pressure.tsx"],
  },
  {
    name: "true-focus",
    title: "True Focus",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/true-focus.tsx"],
  },
  {
    name: "gradient-text",
    title: "Gradient Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/gradient-text.tsx"],
  },
  {
    name: "blur-text",
    title: "Blur Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/blur-text.tsx"],
  },
  {
    name: "split-text",
    title: "Split Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/split-text.tsx"],
  },
  {
    name: "decrypted-text",
    title: "Decrypted Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/decrypted-text.tsx"],
  },
  {
    name: "shimmer-text",
    title: "Shimmer Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/shimmer-text.tsx"],
  },
  {
    name: "floating-text",
    title: "Floating Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/floating-text.tsx"],
  },
  {
    name: "animated-beam",
    title: "Animated Beam",
    category: "Components",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/animated-beam.tsx"],
  },
  {
    name: "border-beam",
    title: "Border Beam",
    category: "Components",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/border-beam.tsx"],
  },
  {
    name: "bento-grid",
    title: "Bento Grid",
    category: "Components",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/bento-grid.tsx"],
  },
  {
    name: "decay-card",
    title: "Decay Card",
    category: "Components",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/decay-card.tsx"],
  },
  {
    name: "scratch-to-reveal",
    title: "Scratch to Reveal",
    category: "Components",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/scratch-to-reveal.tsx"],
  },
  {
    name: "stack",
    title: "Stack",
    category: "Components",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/stack.tsx"],
  },
  {
    name: "star-border",
    title: "Star Border",
    category: "Components",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/star-border.tsx"],
  },
  {
    name: "tilted-card",
    title: "Tilted Card",
    category: "Components",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge", "framer-motion"],
    files: ["registry/tilted-card.tsx"],
  },
  {
    name: "pixel-card",
    title: "Pixel Card",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/pixel-card.tsx"],
  },
  {
    name: "click-spark",
    title: "Click Spark",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/click-spark.tsx"],
  },
  {
    name: "spotlight-card",
    title: "Spotlight Card",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/spotlight-card.tsx"],
  },
  {
    name: "border-glow",
    title: "Border Glow",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/border-glow.tsx"],
  },
] as const satisfies readonly RegistryItem[];

export type ComponentName = (typeof registry)[number]["name"];
