export const registry = [
  {
    name: "magic-button",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/magic-button.tsx"],
  },

  {
    name: "morphing-navbar",
    type: "components:ui",
    dependencies: ["framer-motion", "lucide-react", "clsx", "tailwind-merge"],
    files: ["registry/morphing-navbar.tsx"],
  },
  {
    name: "animated-button",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/animated-button.tsx"],
  },
  {
    name: "pulse-button",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/pulse-button.tsx"],
  },
  {
    name: "rotating-card",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/rotating-card.tsx"],
  },
  {
    name: "floating-text",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/floating-text.tsx"],
  },
  {
    name: "notch-footer",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/notch-footer.tsx"],
  },
  {
    name: "tilt-card",
    type: "components:ui",
    dependencies: ["framer-motion"],
    files: ["registry/tilt-card.tsx"],
  },
  {
    name: "floating-dock",
    type: "components:ui",
    dependencies: ["framer-motion", "lucide-react"],
    files: ["registry/floating-dock.tsx"],
  },
  {
    name: "circuit-background",
    type: "components:ui",
    dependencies: [],
    files: ["registry/circuit-background.tsx"],
  },
  {
    name: "focus-card",
    type: "components:ui",
    dependencies: ["clsx", "tailwind-merge"],
    files: ["registry/focus-card.tsx"],
  },
  {
    name: "expandable-showcase",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/expandable-showcase.tsx"],
  },
  {
    name: "shimmer-text",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/shimmer-text.tsx"],
  },
  {
    name: "kinetic-carousel",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/kinetic-carousel.tsx"],
  },
  {
    name: "process-stepper",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/process-stepper.tsx"],
  },
  {
    name: "animated-list",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/animated-list.tsx"],
  },
  {
    name: "masonry-grid",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/masonry-grid.tsx"],
  },
  {
    name: "aurora-background",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/aurora-background.tsx"],
  },
  {
    name: "grid-motion",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/grid-motion.tsx"],
  },
  {
    name: "blur-text",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/blur-text.tsx"],
  },
  {
    name: "split-text",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/split-text.tsx"],
  },
  {
    name: "decrypted-text",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/decrypted-text.tsx"],
  },
];

