/**
 * The single source of truth for every component. The docs sidebar, the
 * components index, the CLI registry and the tests all read from this list,
 * and `demos.ts` is type-checked against it.
 */
export const CATEGORIES = [
  "Navigation",
  "Actions",
  "Data Display",
  "Backgrounds",
  "Typography",
  "Components",
] as const;

export type Category = (typeof CATEGORIES)[number];

export interface RegistryItem {
  /** Slug used in URLs, file names and `npx @modus-ui/cli add <name>`. */
  name: string;
  title: string;
  category: Category;
  type: "components:ui";
  dependencies: readonly string[];
  files: readonly string[];
}

export const registry = [
  {
    name: "liquid-tabs",
    title: "Liquid Tabs",
    category: "Navigation",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/liquid-tabs.tsx"],
  },
  {
    name: "flowing-menu",
    title: "Flowing Menu",
    category: "Navigation",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/flowing-menu.tsx"],
  },
  {
    name: "morphing-navbar",
    title: "Morphing Navbar",
    category: "Navigation",
    type: "components:ui",
    dependencies: ["next/image", "framer-motion", "lucide-react", "clsx", "tailwind-merge"],
    files: ["registry/morphing-navbar.tsx"],
  },
  {
    name: "floating-dock",
    title: "Floating Dock",
    category: "Navigation",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/floating-dock.tsx"],
  },
  {
    name: "notch-footer",
    title: "Notch Footer",
    category: "Navigation",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/notch-footer.tsx"],
  },
  {
    name: "process-stepper",
    title: "Process Stepper",
    category: "Navigation",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/process-stepper.tsx"],
  },
  {
    name: "magnet",
    title: "Magnet",
    category: "Actions",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/magnet.tsx"],
  },
  {
    name: "magic-button",
    title: "Magic Button",
    category: "Actions",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/magic-button.tsx"],
  },
  {
    name: "animated-button",
    title: "Animated Button",
    category: "Actions",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/animated-button.tsx"],
  },
  {
    name: "pulse-button",
    title: "Pulse Button",
    category: "Actions",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/pulse-button.tsx"],
  },
  {
    name: "bounce-cards",
    title: "Bounce Cards",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/bounce-cards.tsx"],
  },
  {
    name: "masonry-grid",
    title: "Masonry Grid",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/masonry-grid.tsx"],
  },
  {
    name: "animated-list",
    title: "Animated List",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/animated-list.tsx"],
  },
  {
    name: "kinetic-carousel",
    title: "Kinetic Carousel",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/kinetic-carousel.tsx"],
  },
  {
    name: "expandable-showcase",
    title: "Expandable Showcase",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/expandable-showcase.tsx"],
  },
  {
    name: "focus-card",
    title: "Focus Card",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/focus-card.tsx"],
  },
  {
    name: "rotating-card",
    title: "Rotating Card",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/rotating-card.tsx"],
  },
  {
    name: "tilt-card",
    title: "Tilt Card",
    category: "Data Display",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/tilt-card.tsx"],
  },
  {
    name: "cursor-grid",
    title: "Cursor Grid",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/cursor-grid.tsx"],
  },
  {
    name: "waves",
    title: "Waves",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/waves.tsx"],
  },
  {
    name: "letter-glitch",
    title: "Letter Glitch",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/letter-glitch.tsx"],
  },
  {
    name: "aurora-background",
    title: "Aurora Background",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/aurora-background.tsx"],
  },
  {
    name: "circuit-background",
    title: "Circuit Background",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/circuit-background.tsx"],
  },
  {
    name: "orbiting-elements",
    title: "Orbiting Elements",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/orbiting-elements.tsx"],
  },
  {
    name: "blob-cursor",
    title: "Blob Cursor",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/blob-cursor.tsx"],
  },
  {
    name: "magnet-lines",
    title: "Magnet Lines",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/magnet-lines.tsx"],
  },
  {
    name: "grid-motion",
    title: "Grid Motion",
    category: "Backgrounds",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/grid-motion.tsx"],
  },
  {
    name: "gravity-text-swap",
    title: "Gravity Text Swap",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/gravity-text-swap.tsx"],
  },
  {
    name: "flip-words",
    title: "Flip Words",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/flip-words.tsx"],
  },
  {
    name: "fuzzy-text",
    title: "Fuzzy Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/fuzzy-text.tsx"],
  },
  {
    name: "scroll-velocity",
    title: "Scroll Velocity",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/scroll-velocity.tsx"],
  },
  {
    name: "text-pressure",
    title: "Text Pressure",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/text-pressure.tsx"],
  },
  {
    name: "true-focus",
    title: "True Focus",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/true-focus.tsx"],
  },
  {
    name: "gradient-text",
    title: "Gradient Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/gradient-text.tsx"],
  },
  {
    name: "blur-text",
    title: "Blur Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/blur-text.tsx"],
  },
  {
    name: "split-text",
    title: "Split Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/split-text.tsx"],
  },
  {
    name: "decrypted-text",
    title: "Decrypted Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/decrypted-text.tsx"],
  },
  {
    name: "shimmer-text",
    title: "Shimmer Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/shimmer-text.tsx"],
  },
  {
    name: "floating-text",
    title: "Floating Text",
    category: "Typography",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/floating-text.tsx"],
  },
  {
    name: "animated-beam",
    title: "Animated Beam",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/animated-beam.tsx"],
  },
  {
    name: "border-beam",
    title: "Border Beam",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/border-beam.tsx"],
  },
  {
    name: "bento-grid",
    title: "Bento Grid",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/bento-grid.tsx"],
  },
  {
    name: "decay-card",
    title: "Decay Card",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/decay-card.tsx"],
  },
  {
    name: "scratch-to-reveal",
    title: "Scratch to Reveal",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/scratch-to-reveal.tsx"],
  },
  {
    name: "stack",
    title: "Stack",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/stack.tsx"],
  },
  {
    name: "star-border",
    title: "Star Border",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/star-border.tsx"],
  },
  {
    name: "tilted-card",
    title: "Tilted Card",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/tilted-card.tsx"],
  },
  {
    name: "pixel-card",
    title: "Pixel Card",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/pixel-card.tsx"],
  },
  {
    name: "click-spark",
    title: "Click Spark",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/click-spark.tsx"],
  },
  {
    name: "spotlight-card",
    title: "Spotlight Card",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/spotlight-card.tsx"],
  },
  {
    name: "border-glow",
    title: "Border Glow",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/border-glow.tsx"],
  },
  {
    name: "comparison-slider",
    title: "Comparison Slider",
    category: "Components",
    type: "components:ui",
    dependencies: ["lucide-react", "framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/comparison-slider.tsx"],
  },
  {
    name: "dock",
    title: "Dock",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/dock.tsx"],
  },
  {
    name: "progress-ring",
    title: "Progress Ring",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/progress-ring.tsx"],
  },
  {
    name: "marquee",
    title: "Marquee",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/marquee.tsx"],
  },
  {
    name: "reflective-card",
    title: "Reflective Card",
    category: "Components",
    type: "components:ui",
    dependencies: ["lucide-react", "framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/reflective-card.tsx"],
  },
  {
    name: "fluid-glass",
    title: "Fluid Glass",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/fluid-glass.tsx"],
  },
  {
    name: "dome-gallery",
    title: "Dome Gallery",
    category: "Components",
    type: "components:ui",
    dependencies: ["@use-gesture/react", "framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/dome-gallery.tsx"],
  },
  {
    name: "chroma-grid",
    title: "Chroma Grid",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/chroma-grid.tsx"],
  },
  {
    name: "bell-toggle",
    title: "Bell Toggle",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "framer-motion",
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/bell-toggle.tsx"],
  },
  {
    name: "branched-menu",
    title: "Branched Menu",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "framer-motion",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/branched-menu.tsx"],
  },
  {
    name: "call-chip",
    title: "Call Chip",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "framer-motion",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/call-chip.tsx"],
  },
  {
    name: "code-slots",
    title: "Code Slots",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "framer-motion",
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/code-slots.tsx"],
  },
  {
    name: "comet-dial",
    title: "Comet Dial",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/comet-dial.tsx"],
  },
  {
    name: "dodge-field",
    title: "Dodge Field",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/dodge-field.tsx"],
  },
  {
    name: "flip-card",
    title: "Flip Card",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/flip-card.tsx"],
  },
  {
    name: "folder-float",
    title: "Folder Float",
    category: "Components",
    type: "components:ui",
    dependencies: ["matter-js", "framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/folder-float.tsx"],
  },
  {
    name: "fuse-button",
    title: "Fuse Button",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "framer-motion",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/fuse-button.tsx"],
  },
  {
    name: "glide-select",
    title: "Glide Select",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "framer-motion",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/glide-select.tsx"],
  },
  {
    name: "hold-button",
    title: "Hold Button",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/hold-button.tsx"],
  },
  {
    name: "jelly-radio",
    title: "Jelly Radio",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/jelly-radio.tsx"],
  },
  {
    name: "lattice-loader",
    title: "Lattice Loader",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/lattice-loader.tsx"],
  },
  {
    name: "paper-crumple",
    title: "Paper Crumple",
    category: "Components",
    type: "components:ui",
    dependencies: ["three", "framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/paper-crumple.tsx"],
  },
  {
    name: "peek-rating",
    title: "Peek Rating",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "framer-motion",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/peek-rating.tsx"],
  },
  {
    name: "prompt-bar",
    title: "Prompt Bar",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "framer-motion",
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/prompt-bar.tsx"],
  },
  {
    name: "pulse-heart",
    title: "Pulse Heart",
    category: "Components",
    type: "components:ui",
    dependencies: ["@hugeicons/core-free-icons", "framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/pulse-heart.tsx"],
  },
  {
    name: "refine-frame",
    title: "Refine Frame",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "framer-motion",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/refine-frame.tsx"],
  },
  {
    name: "rubber-segment",
    title: "Rubber Segment",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/rubber-segment.tsx"],
  },
  {
    name: "scrub-field",
    title: "Scrub Field",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/scrub-field.tsx"],
  },
  {
    name: "shredder",
    title: "Shredder",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/shredder.tsx"],
  },
  {
    name: "slide-commit",
    title: "Slide Commit",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "framer-motion",
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/slide-commit.tsx"],
  },
  {
    name: "sling-button",
    title: "Sling Button",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "framer-motion",
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/sling-button.tsx"],
  },
  {
    name: "slosh-gauge",
    title: "Slosh Gauge",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/slosh-gauge.tsx"],
  },
  {
    name: "spring-check",
    title: "Spring Check",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "@hugeicons/core-free-icons", "clsx", "tailwind-merge"],
    files: ["registry/spring-check.tsx"],
  },
  {
    name: "squish-switch",
    title: "Squish Switch",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/squish-switch.tsx"],
  },
  {
    name: "status-mark",
    title: "Status Mark",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/status-mark.tsx"],
  },
  {
    name: "swipe-row",
    title: "Swipe Row",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "framer-motion",
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/swipe-row.tsx"],
  },
  {
    name: "swipe-toast",
    title: "Swipe Toast",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "framer-motion",
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/swipe-toast.tsx"],
  },
  {
    name: "tear-ticket",
    title: "Tear Ticket",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/tear-ticket.tsx"],
  },
  {
    name: "thought-line",
    title: "Thought Line",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "framer-motion",
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/thought-line.tsx"],
  },
  {
    name: "voice-pill",
    title: "Voice Pill",
    category: "Components",
    type: "components:ui",
    dependencies: [
      "@hugeicons/react",
      "@hugeicons/core-free-icons",
      "framer-motion",
      "clsx",
      "tailwind-merge",
    ],
    files: ["registry/voice-pill.tsx"],
  },
  {
    name: "wake-slider",
    title: "Wake Slider",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/wake-slider.tsx"],
  },
  {
    name: "warm-tooltip",
    title: "Warm Tooltip",
    category: "Components",
    type: "components:ui",
    dependencies: ["framer-motion", "clsx", "tailwind-merge"],
    files: ["registry/warm-tooltip.tsx"],
  },
] as const satisfies readonly RegistryItem[];

export type ComponentName = (typeof registry)[number]["name"];
